import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { Nav } from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 5 - Layout */}
        <h1>Cabeçalho do site</h1>
        {/* 8 - Link ativo */}
        <Nav />
        {children}
        {/* 6 - Componentes */}
        <Footer />
      </body>
    </html>
  );
}
